name: Call a reusable workflow

on:
  push:
    branches: [master]

jobs:
  calling-the-reusable-workflow:
    uses: minhnghia2k3/doc-examples/.github/workflows/reusable.yml@master
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
